export const RasKucing = [
  'Persia',
  'Anggora',
  'Maine Coon',
  'Siamese',
  'Bengal',
  'Ragdoll',
  'British Shorthair',
  'Scottish Fold',
  'Sphynx',
  'Abyssinian',
  'Russian Blue',
  'Burmese',
  'American Shorthair',
  'Turkish Van',
  'Norwegian Forest',
  'Oriental Shorthair',
  'Savannah',
  'Devon Rex',
  'Himalayan',
  'Manx',
];
